version: '3.3'
services: 
  db: 
    image: postgres
  migration:
    build: .
    command: python3 Django/Practice/manage.py migrate
    volumes:
    - .:/usr/local/app
    depends_on:
    - db
  web:
    build: .
    command: python3 Django/Practice/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/local/app
    ports:
    - "8000:8000"
    depends_on:
    - db
    - migration
